language: rust
rust:
  - stable
  - beta
  - nightly

services:
  - mysql

env:
  - DATABASE_URL=mysql://travis:@127.0.0.1/EMTM_TEST

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - autoconf
      - curl
      - gcc
      - make
      - tcl
      - mysql-server
      - mysql-client

git:
  submodules: true

before_install:
  - sh ./scripts/setup_test_db.sh

script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --test-threads=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

