version: '3'
services:
  db:
    image: mysql:5.7
    # ports: 
    #   - "9877:3306"
    environment:
      MYSQL_DATABASE: 'EMTM'
      MYSQL_USER: 'emtm'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'EMTM_PASSWORD'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ROOT_PASSWORD'
    expose:
      - '3306'
    volumes:
      - ./emtm-data:/var/lib/mysql
    env_file:
      - .env

  emtm:
    image: emtm-service
    ports:
    - "6789:6789"
    depends_on:
    - db
    # - migration
    links:
    - db
    env_file:
      - .env
    volumes:
      - ./scripts:/usr/src/emtm/scripts
    entrypoint: "bash /usr/src/emtm/scripts/entrypoint.sh"
    environment: 
      - EMTM_LOG=info
      - DATABASE_URL=mysql://root:ROOT_PASSWORD@db:3306/EMTM

  # migration:
  #   image: emtm-service
  #   command: "cd /usr/src/emtm/emtm-db && diesel setup"
  #   depends_on:
  #   - db
  #   links:
  #   - db
  #   env_file:
  #     - .env

