version: '3'
services:
  db:
    image: mysql:5.7
    # ports: 
    #   - "9877:3306"
    environment:
      MYSQL_DATABASE: 'EMTM'
      MYSQL_USER: 'emtm'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'EMTM_PASSWORD'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ROOT_PASSWORD'
    expose:
      - '3306'
    volumes:
      - ./emtm-data:/var/lib/mysql
    env_file:
      - .env

  emtm:
    image: emtm-service
    ports:
    - "6789:6789"
    depends_on:
    - db
    links:
    - db
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
    entrypoint: "bash /scripts/wait-for-it.sh 127.0.0.1:3306"

  migration:
    image: emtm-service
    command: "cd /usr/src/emtm/emtm-db && ls -la"
    depends_on:
    - db
    links:
    - db
    env_file:
      - .env

